### ISSUE TITLE
echo \\

### ISSUE THREAD

**Issue by gabriela-freitas** [gabriela-freitas/minishell#19]
![image](https://user-images.githubusercontent.com/85411324/183455990-b41cb228-785f-477e-be4b-5f9e9e81441c.png)

**Comment by mfreixlo** [comment]
Acho que nao nos temos de preocupar com os backslash
![image](https://user-images.githubusercontent.com/93141616/184485625-b4a3bbc0-4601-4d5e-9416-57aa93e051a2.png)

E por algum motivo ja nao esta a dar seg fault, por isso acho que isto ja nao e um issue
![image](https://user-images.githubusercontent.com/93141616/184486062-c9956274-67be-4689-b674-8e29f5426b03.png)
