### ISSUE TITLE
seg fault with ""

### ISSUE THREAD

**Issue by gabriela-freitas** [gabriela-freitas/minishell#25]
![image](https://user-images.githubusercontent.com/85411324/183985347-bdf76c8d-ce7e-41cd-b7ce-53755ab255c4.png)

**Comment by mfreixlo** [comment]
Theres no more seg fault there!! 🥇 💯 
![image](https://user-images.githubusercontent.com/93141616/184488653-0d7fbec2-c8c5-4582-aef2-5d18ca28b644.png)

But there's this mistake with backslash, I think we can ignore it, because the subject says we dont have to deal with it

**Comment by mfreixlo** [comment]
For me this issue is closed!

**Comment by gabriela-freitas** [comment]
I agree we can ignore it!!
