### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by mfreixlo** [gabriela-freitas/minishell#30]
- [x]  Print the error everytime something goes wrong
- [x] Save last error's code and its message
- [x] Print the error and messge with $?

**Comment by mfreixlo** [comment]
![image](https://user-images.githubusercontent.com/93141616/187711939-40389b0e-549f-4de7-9133-e4eb90549d96.png)
here, the last echo $? should print 0

**Comment by mfreixlo** [comment]
![image](https://user-images.githubusercontent.com/93141616/187715209-f16186ed-be86-45d5-9018-c8c1dabf59e6.png)

**Comment by gabriela-freitas** [comment]
Everything we've tested so far is working smoothly.
