### ISSUE TITLE
Export + echo

### ISSUE THREAD

**Issue by mfreixlo** [gabriela-freitas/minishell#31]
>> Export e=
>> Echo $e
>>
>> Echo $e=
     =
>>Echo $=
     $=

Echo $VAR= if there's a = after $ the name of variable stops there, so we have to print the =

**Comment by mfreixlo** [comment]
Marta, acho que o problema é no expansion

**Comment by mfreixlo** [comment]
> >> Export e=
> >> Echo $e
> >>
> >> Echo $e=
>      =
> >>Echo $=
>      $=
> 
> Echo $VAR= if there's a = after $ the name of variable stops there, so we have to print the =

Marta, acho que o problema é no expansion

**Comment by mfreixlo** [comment]
If there's a variable with invalid identifiers print the error with the wrong identifier

**Comment by mfreixlo** [comment]
Export has to consider the case when '=' is in the value of the new variable
![image](https://user-images.githubusercontent.com/93141616/184869160-299adf15-abcf-490f-b9db-6459d52ece1e.png)

**Comment by mfreixlo** [comment]
![image](https://user-images.githubusercontent.com/93141616/184872603-f5e94fda-6d18-4f10-b7b1-09aa23d4dd12.png)

**Comment by gabriela-freitas** [comment]
![image](https://user-images.githubusercontent.com/85411324/185678413-ab36859c-8eb7-48b0-ac2c-d38fb94a5b28.png)
I think it's closedd

**Comment by mfreixlo** [comment]
Omg lindo 😍
