### ISSUE TITLE
Ctrl+C and wc with no args

### ISSUE THREAD

**Issue by gabriela-freitas** [gabriela-freitas/minishell#38]

**Comment by gabriela-freitas** [comment]
The signal was being interpreted twice, so I added a signal block at the parent process of the execution function.

**Comment by mfreixlo** [comment]
When we executed in pipes, such as "wc | cat" the sig_block was interpreted twice and printed two new_lines. We had to create a new sig_block funtion with no new_line to be added in pipex.c/loop_pipex() function.

![image](https://user-images.githubusercontent.com/93141616/198703739-8db69bc7-bc5c-4f5d-94ed-e8cca602e0c5.png)
