### ISSUE TITLE
Random errors with echo

### ISSUE THREAD

**Issue by mfreixlo** [gabriela-freitas/minishell#40]
![image](https://user-images.githubusercontent.com/93141616/187029482-65d2a494-1494-4450-820c-dde2ed85ff4a.png)

**Comment by mfreixlo** [comment]
![image](https://user-images.githubusercontent.com/93141616/187029508-221046d9-db87-4bb1-97f4-4eca2aba3dd4.png)

**Comment by mfreixlo** [comment]
![image](https://user-images.githubusercontent.com/93141616/187029518-a500a0dc-9dfc-4351-b5f5-123e945c8e01.png)

**Comment by mfreixlo** [comment]
![image](https://user-images.githubusercontent.com/93141616/187029616-d7f16bf0-291c-48d5-8226-c53f19618539.png)

**Comment by mfreixlo** [comment]
I think every time we echo something that ends with an \ it gives error

**Comment by gabriela-freitas** [comment]
Gabi agrees with Marta
