### ISSUE TITLE
input ending with "\

### ISSUE THREAD

**Issue by mfreixlo** [gabriela-freitas/minishell#48]
![image](https://user-images.githubusercontent.com/93141616/187768748-b6091718-c917-4da2-96e8-f1df4d77a022.png)

input finishing with "\

**Comment by gabriela-freitas** [comment]
![image](https://user-images.githubusercontent.com/85411324/187971973-0242e618-bc78-46c9-ade2-35bec580d968.png)
![image](https://user-images.githubusercontent.com/85411324/187972071-f74acd03-83fa-462d-8fc8-22694c55d51c.png)

everything apparently okkk
