### ISSUE TITLE
export | grep

### ISSUE THREAD

**Issue by mfreixlo** [gabriela-freitas/minishell#49]
![image](https://user-images.githubusercontent.com/93141616/187770442-a026732d-f3d0-47fd-aaa8-e679a18816f0.png)

**Comment by mfreixlo** [comment]
when exporting without arguments, the variable is not set in export!
So it doesnt appear when we grep with nor when input is export

**Comment by gabriela-freitas** [comment]
![image](https://user-images.githubusercontent.com/85411324/187986134-42f3b717-1159-4b94-9924-ae055e604518.png)
![image](https://user-images.githubusercontent.com/85411324/187986212-5f9c503f-3ea2-44d5-839c-9359ab57eeb0.png)

everything beautiful and formatted
