### ISSUE TITLE
Starting command with redirection

### ISSUE THREAD

**Issue by mfreixlo** [gabriela-freitas/minishell#53]
![image](https://user-images.githubusercontent.com/93141616/198988920-f090551f-69ba-4160-9800-f02638aa3b48.png)

**Comment by mfreixlo** [comment]
> 

It should just create the file cat and not try to run the INEXISTENT command

**Comment by mfreixlo** [comment]
![image](https://user-images.githubusercontent.com/93141616/198989181-ef96d6dc-9bef-4bec-b7fa-14dda2c338c8.png)

We are creating the file, but then when removing it, it gives an error....

**Comment by gabriela-freitas** [comment]
The parsing was returning an array of strings with the first one empty but the other were good, so I added a condition on execution and now works good
![image](https://user-images.githubusercontent.com/85411324/199057045-9f586590-4568-4a3f-9e56-6ac1fcfffe82.png)
![image](https://user-images.githubusercontent.com/85411324/199057130-7abe1573-39ae-4ba7-ad44-cce8b86a013e.png)
![image](https://user-images.githubusercontent.com/85411324/199057166-4070eee2-a454-4f94-a5eb-4e27f21b6489.png)
