### ISSUE TITLE
Parsing do $

### ISSUE THREAD

**Issue by gabriela-freitas** [gabriela-freitas/minishell#9]

**Comment by gabriela-freitas** [comment]
![WhatsApp Image 2022-08-02 at 16 27 49](https://user-images.githubusercontent.com/85411324/182413000-271ed264-93d7-406d-9ee7-a959912056e8.jpeg)

**Comment by mfreixlo** [comment]
- [ ] echo $HOME"$" (ignore the quotes, this puts HOME in italic without the quotes"), it just prints the value of $HOME, but does not print the $ in the end
- [ ] 
![image](https://user-images.githubusercontent.com/93141616/184484824-5c1ff388-0994-4f66-8a68-0e43f929eef2.png)
